"""add timestamps to documents and memories

Revision ID: 8ab8a8a441f9
Revises: fa855c67805f
Create Date: 2026-08-21 14:00:04.552781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab8a8a441f9'
down_revision: Union[str, Sequence[str], None] = 'fa855c67805f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('memories', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('memories', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'updated_at')
    op.drop_column('memories', 'created_at')
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    # ### end Alembic commands ###
