"""add created_at to operational tables

Revision ID: fa855c67805f
Revises: b8998f3a0776
Create Date: 2026-08-21 13:10:23.749523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa855c67805f'
down_revision: Union[str, Sequence[str], None] = 'b8998f3a0776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('audit_logs', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tool_calls', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_calls', 'created_at')
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('approvals', 'created_at')
    # ### end Alembic commands ###
